"""Plot CF distribution from CSV file(s) (generated by cf.py).

Usage:
  python scripts/plot_cf_dist.py --csv results/csv/imagenet_val5k_cf.csv
  python scripts/plot_cf_dist.py --csv results/csv/imagenet_val5k_cf.csv --exclude_gray
  python scripts/plot_cf_dist.py --csv results/csv/gt_cf.csv --csv2 results/csv/gen_cf.csv
"""

import argparse
import os
import csv

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Style (consistent with plot_curves.py)
# ------------------------------------------------------------
plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'SimSun'],
    'axes.unicode_minus': False,
    'font.size': 13,
    'axes.labelsize': 15,
    'axes.titlesize': 16,
    'legend.fontsize': 13,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
    'lines.linewidth': 1.5,
    'axes.grid': True,
    'grid.alpha': 0.3,
    'grid.linestyle': '--',
    'savefig.bbox': 'tight',
    'savefig.dpi': 300,
})

DPI = 300
FIGSIZE = (9, 6)
GRAY_THRESHOLD = 1.0


def load_cf(csv_path):
    vals = []
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            vals.append(float(row['cf']))
    return np.array(vals)


def extract_name(path):
    return os.path.splitext(os.path.basename(path))[0]


def main():
    parser = argparse.ArgumentParser(description='Plot CF distribution from CSV')
    parser.add_argument('--csv', type=str, required=True, help='Path to CF CSV file')
    parser.add_argument('--csv2', type=str, default=None, help='Second CSV for comparison')
    parser.add_argument('--exclude_gray', action='store_true',
                        help='Exclude grayscale images (CF < 1.0) and report mean')
    args = parser.parse_args()

    # 1. Load data
    cf1 = load_cf(args.csv)
    datasets = [(cf1, extract_name(args.csv), 'steelblue', 'red')]

    if args.csv2:
        cf2 = load_cf(args.csv2)
        datasets.append((cf2, extract_name(args.csv2), 'darkorange', 'darkorange'))

    # 2. Statistics
    for cf, name, _, _ in datasets:
        print(f'--- {name} ---')
        print(f'  Total: {len(cf)}')
        print(f'  Mean:  {cf.mean():.2f}')
        print(f'  Std:   {cf.std():.2f}')
        if args.exclude_gray:
            cf_color = cf[cf >= GRAY_THRESHOLD]
            print(f'  Color images: {len(cf_color)}')
            print(f'  Mean (color): {cf_color.mean():.2f}')
            print(f'  Std  (color): {cf_color.std():.2f}')
        print()

    # 3. Plot
    fig, ax = plt.subplots(figsize=FIGSIZE)
    bin_width = 2
    bins = np.arange(0, 160 + bin_width, bin_width)

    for cf, name, color, mean_color in datasets:
        ax.hist(cf, bins=bins, alpha=0.55, color=color, edgecolor='white')
        ax.axvline(cf.mean(), color=mean_color, linestyle='--', linewidth=2)

        if args.exclude_gray:
            cf_color = cf[cf >= GRAY_THRESHOLD]
            if len(cf_color) > 0:
                ax.axvline(cf_color.mean(), color=mean_color, linestyle='-', linewidth=2)

    ax.set_xlabel('Colorfulness (CF)')
    ax.set_ylabel('图片数量')
    ax.set_xlim(0, 160)
    ax.set_ylim(0, 300)

    plt.tight_layout()

    # 4. Save
    out_dir = os.path.dirname(args.csv)
    if args.csv2:
        base = f'{extract_name(args.csv)}_vs_{extract_name(args.csv2)}'
    else:
        base = extract_name(args.csv)
    suffix = '_color_only' if args.exclude_gray else ''
    out_path = os.path.join(out_dir, f'{base}_dist{suffix}.png')
    plt.savefig(out_path, dpi=DPI)
    plt.close()
    print(f'Saved: {out_path}')


if __name__ == '__main__':
    main()
